spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com/
          predicates:
          - Query=baidu

        - id: qq_route
          uri: https://www.qq.com/
          predicates:
          - Query=qq
